# -*- coding: utf-8 -*-
__author__ = 'vahid'

DEFAULT_HEADER = """
# Generated by `networking-interfaces`. A python library to manage /etc/network/interfaces file.
# You may manually edit this file. But it may be rewritten by the library.
"""
